name = "rx-pad"
compatibility_date = "2026-03-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[vars]
RX_PAD_BOOTSTRAP_MODE = "production"

# Local/default D1 binding
[[d1_databases]]
binding = "DB"
database_name = "rx-pad"
database_id = "7e1a7c7a-f70f-4a09-9ea6-3d2b5cfc47d2"

[env.preview.vars]
RX_PAD_BOOTSTRAP_MODE = "preview"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "rx-pad-test"
database_id = "45c2ced8-6814-4a3c-ba16-8278eabfe814"

[env.production.vars]
RX_PAD_BOOTSTRAP_MODE = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "rx-pad"
database_id = "7e1a7c7a-f70f-4a09-9ea6-3d2b5cfc47d2"
